### ISSUE TITLE
Repository does not adhere to license of original code.

### ISSUE THREAD

**Issue by duncte123** [appujet/jiosaavn-plugin#1]
[skybot]: https://github.com/DuncteBot/skybot-lavalink-plugin

This repository includes code from the [Skybot Plugin][skybot], which is licensed under the apache2 license.

Rights and requirements/conditions for this license are as follows:
![image](https://github.com/appujet/jiosaavan-plugin/assets/8843386/0cff89fd-5de9-4c0c-9729-99e896482bd1)

Please add the required license information back into the code as is required.

Thank you for your cooperation.

**Comment by appujet** [comment]
yes but i am not done to finish i will give proper credit

**Comment by duncte123** [comment]
> yes but i am not done to finish i will give proper credit

That is not how license conditions work. The moment you pull in code from other projects is when you need to credit them.

**Comment by appujet** [comment]
will i am making new code
